apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: telegram-receiver
        type: telegram
        settings:
          bottoken: ${TELEGRAM_BOT_TOKEN}
          chatid: "475540258"
          message: |
            {{ if eq .Status "firing" }}🔴{{ else }}🟢{{ end }} {{ .CommonLabels.alertname }}
            {{ range .Alerts }}
            {{ if .Annotations.summary }}{{ .Annotations.summary }}{{ end }}
            {{ if .Annotations.description }}{{ .Annotations.description }}{{ end }}
            {{ end }}
        disableResolveMessage: false
