build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

comments:
  active: false

complexity:
  active: true
  CyclomaticComplexMethod:
    threshold: 15
  LongMethod:
    threshold: 60
  LongParameterList:
    active: false
  TooManyFunctions:
    active: false

coroutines:
  active: true

empty-blocks:
  active: true

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
  ClassNaming:
    active: true

performance:
  active: true

potential-bugs:
  active: true
  UnsafeCallOnNullableType:
    active: true

style:
  active: true
  FunctionOnlyReturningConstant:
    active: false
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  WildcardImport:
    active: false
  UnusedPrivateMember:
    active: true
  ForbiddenComment:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
